### ISSUE TITLE
Profile & optimise movedata2networkDynamic

### ISSUE THREAD

**Issue by CarlijnB** [digivet-consortium/movenet#36]
movedata2networkDynamic slowed down considerably when I added code to change identifiers to consecutive integers, and store original identifiers as pid's.
(I believe I've commented out some unnecessary tests etc. but not sure whether this makes any difference)

Profile to identify slow bits - recommended to use profvis https://rstudio.github.io/profvis/
Optimise

**Comment by KangarooWasp** [comment]
I've run profvis on the function, it seems that movedata2networkDynamic is spending pretty much all of its time in the reconcile.vertex.activity function from the networkDynamic package. I don't think it's possible to make that run faster, but maybe we could make that part optional in case some library users don't need to use node activity spells?

**Comment by CarlijnB** [comment]
Thank you @KangarooWasp !  Yes, it makes sense that that is slow (I think it says so in the networkDynamic documentation too). I'll try to think of implications of taking it out.

**Comment by CarlijnB** [comment]
One way of making "reconcile.vertex.activity" optional, but still getting the same results, would be to pass vertex.spell data to networkDynamic at the start. We can just manipulate the original movement data tibble to get node activity spells from there.

**Comment by CarlijnB** [comment]
@KangarooWasp I've just committed a new version of movedata2networkDynamic in the profile-and-optimise-movedata2networkDynamic branch. Please could you profile this and let me know if there are any further steps where it seems to take lots of time?

It'd be also great if you could profile the function if you add holding data with more farms than are included in the movement data:
On the same Github branch I've added a smaller test dataset, movement_data_halved.csv, with movements to/from 248 farms. Use this to create a movement_data tibble, but then use the ORIGINAL, larger test dataset to get a holding_data tibble (with 500 farms), then pass both the movement_data and the holding_data to movedata2networkDynamic.

**Comment by KangarooWasp** [comment]
I've run the profiling again.
Here are the results for the full dataset (taking 1300ms to run):
![New profiling results with full dataset](https://github.com/digivet-consortium/movenet/assets/85952810/006816cb-5995-4870-9e02-b2b2e62e92b5)
And here are the results for the smaller dataset you provided (taking only 180ms):
![New profiling results with smaller dataset](https://github.com/digivet-consortium/movenet/assets/85952810/c9be77af-b239-40f4-bef4-70e889b93fc0)

![Original profiling results](https://github.com/digivet-consortium/movenet/assets/85952810/40154105-c249-4b41-8649-fd398ae9402b)

**Comment by CarlijnB** [comment]
Awesome, thank you so much! Great to see this has sped the function up so much.
That second picture, is that with the smaller dataset and the larger holding data - running movedata2networkDynamic(movement_data, holding_data)? asking because this should have some additional code blocks to run ...

**Comment by KangarooWasp** [comment]
Yes, the second picture is with the smaller data set, with the movement data from `movement_data_halved.csv` and the holding data from `test_holdingdata_generic.csv`. If there are some missing function calls in the diagram then it might just be omitting ones that run too fast for it to record them?

**Comment by CarlijnB** [comment]
Great, thank you for confirming.  It's good to know that [if all actually works as it should], including holding data does not slow the function down.

I have to admit I struggle to completely follow the diagram, as there's too many calls to generic functions like lapply, and not all network-specific functions are labelled. But I think you're right regarding it omitting fast-running processes etc., and whatever is not labelled also doesn't seem to be a bottleneck.

**Comment by KangarooWasp** [comment]
Is there anything else that needs done before this can be merged? Maybe I can add a new test that checks that the vertex spells are all correct?
If we do that it might also make sense to break some of the code out of movedata2networkDynamic and into a few smaller functions that do the different steps; that'll make the code more readable and also make it easier to write more useful tests.
I can get started on this if you think it's a good idea?
