### ISSUE TITLE
Testing helper function split in movedata2networkDynamic

### ISSUE THREAD

**Issue by CarlijnB** [digivet-consortium/movenet#40]

**Comment by magicicada** [comment]
create_vertex_spells 
- internal and not easy to test?

are_ids_consec_intchars_from_1 
- test a positive
- test a negative

holdingids2consecints
- test a normal small instance
- check an empty input

**Comment by magicicada** [comment]
Proposed plan is to write the simple tests for are_ids_consec_intchars_from_1 and holdingids2consecints, ignore create_vertex_spells, and then close issue

**Comment by KangarooWasp** [comment]
tests added in e4831e8
