### ISSUE TITLE
function to plot degree distribution of movement data in igraph

### ISSUE THREAD

**Issue by magicicada** [digivet-consortium/movenet#6]
ideally dump into automated markdown report

**Comment by CarlijnB** [comment]
- [ ] Change to "complementary cumulative distribution function", see http://networksciencebook.com/chapter/4#advanced-b and image below (from Stefan Widgren) 
- [ ] Add also for incoming and outgoing contact chains 

![4b1e4007-a849-41c7-83fb-a0fdcea61bb8](https://user-images.githubusercontent.com/11770277/173354517-10117021-3850-4de9-9d81-687dbe215d90.jpg)
