### ISSUE TITLE
load_config / validate_config not resulting in intended error when given datafile

### ISSUE THREAD

**Issue by CarlijnB** [digivet-consortium/movenet#60]
Load_config / validate_config need additional testing.
If given a datafile (movement_data.csv), instead of the intended message "... is not a valid movenet config file" with additional failed validation message "is not valid yaml format",  error and traceback are as follows:

```
Error in yamlfile[[paste0(config_type, "data_fileopts")]] :
 subscript out of bounds

3. validate_config_datatype(yamlfile, config_type) at validate_config.R#38
2. internal_validate_config(file) at validate_config.R#18
1. validate_config("C:/Users/cboga/OneDrive - University of Glasgow/CS3-ASF/movenetapp/data-raw/movement_data.csv")
```

**Comment by CarlijnB** [comment]
- validate_yaml yields TRUE - i.e. datafile can be read as yaml
- in internal_validate_config line 37, config_type is then set as "NA".
- validate_config_root gives the intended error message
- validate_config_fileopts does NOT give any message, because config_type = NA (not coded for this eventuality)
- validate_config_cols does NOT give any message, because config_type = NA (not coded for this eventuality)
- validate_config_datatype gives the eventual error in line 119, because config_type = NA (not coded for this eventuality)

**Comment by magicicada** [comment]
Suggested change: in file https://github.com/digivet-consortium/movenet/blob/main/R/validate_config.R
add a check that config_type is not NA after line 37, and if it is then add to error message

**Comment by magicicada** [comment]
Fix in main
